### ISSUE TITLE
Add name and version label

### ISSUE THREAD

**Issue by dzarda** [RoboticsBrno/Zelvicka#21]

**Comment by TVavrinec** [comment]
The question is, what do we want to write next?
![image](https://github.com/RoboticsBrno/Zelvicka/assets/40397963/45011c5c-410c-4cf0-863f-bbdd7c1a1fea)

**Comment by dzarda** [comment]
Designed by Tomáš Vavrinec

**Comment by TVavrinec** [comment]
What do you think about that?
![image](https://github.com/RoboticsBrno/Zelvicka/assets/40397963/79e2b4cd-5338-4037-9768-9ad2bbad8607)

**Comment by dzarda** [comment]
Maybe add "IOxx" labels to sensors

**Comment by dzarda** [comment]
Add servo and iled labels from top side.

1. I want to know what the connector is (ILED, SERVO)
2. I want to know the pin it's connected to

**Comment by TVavrinec** [comment]
Servo labels
![image](https://github.com/RoboticsBrno/Zelvicka/assets/40397963/ce8f6aec-68e6-4a68-8000-7c2db1dff1b2)

Sensor labels
![image](https://github.com/RoboticsBrno/Zelvicka/assets/40397963/618a6d24-884c-41b4-9fce-cf0601d15a0f)
