### ISSUE TITLE
Increase BAT_SENSE divider reduction

### ISSUE THREAD

**Issue by dzarda** [RoboticsBrno/Zelvicka#30]
![obrazek](https://github.com/RoboticsBrno/Zelvicka/assets/3955056/3d1ed25f-9c6a-4806-b06b-e6463009e814)
This gets you 3.318V for 4.35V cell voltage, which is bad.

**Comment by TVavrinec** [comment]
I think you have the wrong version
![image](https://github.com/RoboticsBrno/Zelvicka/assets/40397963/b65d24b0-85c7-47e7-9314-e2569f9e5eb0)

**Comment by TVavrinec** [comment]
What do you think about that?
![image](https://github.com/RoboticsBrno/Zelvicka/assets/40397963/0bdfa532-73f3-4830-8a16-b5643d06b3cf)

**Comment by dzarda** [comment]
That would not work. I'd go with 2x 17.4k

**Comment by TVavrinec** [comment]
Oh, I switched them, sorry I missed the text under the picture.
If I want 0.95V at the output (so I don't need a divider in the ESP), I want this.
![image](https://github.com/RoboticsBrno/Zelvicka/assets/40397963/062688ac-4c8d-4456-a297-cd981c5a4af4)

**Comment by dzarda** [comment]
ok

**Comment by dzarda** [comment]
Actually this gives you tau of cca 1s. Isnt it too much?

**Comment by TVavrinec** [comment]
![image](https://github.com/RoboticsBrno/Zelvicka/assets/40397963/36b2d6b2-be41-4c93-bce0-f82bd357ccf1)
