### ISSUE TITLE
What's the deal here?

### ISSUE THREAD

**Issue by dzarda** [RoboticsBrno/Zelvicka#31]
![obrazek](https://github.com/RoboticsBrno/Zelvicka/assets/3955056/fcfcb639-9a87-4387-a64f-6eab2e140117)

**Comment by dzarda** [comment]
![obrazek](https://github.com/RoboticsBrno/Zelvicka/assets/3955056/d1cc5a58-cea0-4ed6-8f04-86faf1811299)

**Comment by dzarda** [comment]
![obrazek](https://github.com/RoboticsBrno/Zelvicka/assets/3955056/e413cffc-4836-4a0b-b618-bf91a7d2561f)

**Comment by dzarda** [comment]
![obrazek](https://github.com/RoboticsBrno/Zelvicka/assets/3955056/55d34b50-7c18-48aa-8c5d-0abb485b0c5f)

**Comment by dzarda** [comment]
![obrazek](https://github.com/RoboticsBrno/Zelvicka/assets/3955056/5a5e9f48-c83a-49b5-8509-8b68cd451376)

**Comment by dzarda** [comment]
![obrazek](https://github.com/RoboticsBrno/Zelvicka/assets/3955056/e46df37b-5c5a-4fd0-9979-548d63300c60)

**Comment by dzarda** [comment]
![obrazek](https://github.com/RoboticsBrno/Zelvicka/assets/3955056/00683936-27cc-4071-b40a-0aa66cfbd4c1)

**Comment by dzarda** [comment]
![obrazek](https://github.com/RoboticsBrno/Zelvicka/assets/3955056/a4593b2e-37eb-4bfe-9287-b8bf35f2d289)

**Comment by dzarda** [comment]
![obrazek](https://github.com/RoboticsBrno/Zelvicka/assets/3955056/716099ec-b263-45ed-8d89-ffc5760bdb6e)

**Comment by TVavrinec** [comment]
https://github.com/RoboticsBrno/Zelvicka/issues/31#issue-2317285519
https://github.com/RoboticsBrno/Zelvicka/issues/31#issuecomment-2133852155
I don't know exactly what you mean
