### ISSUE TITLE
Maybe add RC filters on LineSensor signals?

### ISSUE THREAD

**Issue by dzarda** [RoboticsBrno/Zelvicka#35]
![obrazek](https://github.com/RoboticsBrno/Zelvicka/assets/3955056/1839114a-0d5a-4929-b1be-0b07c840043d)
Might be a good idea as a defensive mechanism against possible noise from motors for example

**Comment by TVavrinec** [comment]
With a cutoff frequency of about 100 kHz?
If I declare that we can measure faster than 10kHz and we want to do two samples per measurement (real and calibration with ambient light).

**Comment by dzarda** [comment]
Sounds ok
